name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: Castorice4/kernel_build_action@main
        with:
          kernel-url: https://github.com/Castorice4/Xiaomi_Kernel_OpenSource
          kernel-dir: msm-4.14
          kernel-branch: crux-p-oss
          config: crux_user_defconfig
          arch: arm64
          aosp-gcc: true       # 使用 AOSP GCC
          aosp-clang: false    # 禁用 Clang
          android-version: 12
          disable-lto: true
          anykernel3: true
